apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: default
  labels:
    app.kubernetes.io/name: security
  annotations:
    cloud.google.com/load-balancer-type: Internal
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: {{ .Release.Name }}
      protocol: TCP
      port: 80
      targetPort: 80